[package]
name = "matrixMul"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
opt-level = 3
lto = false
debug = false
rpath = false

[dependencies]
rayon = "1.5"